export default [
  [ // Pilot
    `Mathematical!`,
    `Whoa! Algebraic!`,
    `Rhombus! Iceclops!`,
    `MY HAT IS AWESOME!`,
  ],
  [ // Season 1
    `I'm hanging the piñatas... They are all around you! Smash the piñatas!`,
    `Candy People explode when they get scared?`,
    `Slamacow! That was tops! Who's not good at math? I was all, "Four!"`,
    `Tree Trunks, I'm all jacked up because of you. Look at my jacked up face!`,
    `Is that what you think adventurers do? Die and make all your friends feel terrible 'cause they couldn't save you?!`,
    `Do you think I have the goods, Bubblegum? Because I am into this stuff!`,
    `Shmow-zow!`,
    `I'll slay anything that's evil. That's my deal!`,
    `I'm not righteous. I'm wrong-teous. Stupid-teous.`,
    `Baby, I know what you crave.`,
    `Let's get this party started!`,
    `I'll never kidnap again.`,
    `I'm not jealous. I'm weird!`,
    `Uhh.... She hates me now.`,
    `HEY PRINCESS, WANT TO DO THE SCIENCE DANCE WITH ME?`,
    `I feel radder, faster... more adequate!`,
    `I'm Princess Bubblegum and I'm a dork because I like science. I've also got a really annoying voice that Finn thinks is attractive!`,
    `Youth culture forever!`,
    `Are you gonna smash my skull and breathe my blood mist?`,
    `No worms on the bed!`,
    `It's vampire fighting time!`,
    `Get ready for an uppercut, you dog!`,
    `Stealing's wrong, doofus!`,
    `Holy stuff! It talked! Wow-cow-chow!`,
    `What?! You gotta be flipping kidding me!`,
    `(to Fear Feaster) I'm no wuss! I'm the hero around these parts!`,
    `Yeah, it's pretty math... you psychopath!`,
    `Eat my sword, Ice King!`,
    `I'm weddy for the wedding.`,
    `And I felt happy for that son of a toot!`,
    `Heh. Yeah, right. That sounds like idiot talk.`,
    `I'm a radical boy on the mission for the Crystal Eye!`,
    `Whoa, somebody pick up your freaky cat.`,
    `How did you almost know my name?`,
    `Slaps, that cat was kicking my buns, and it might've finished my buns it if weren't for Jake's stank.`,
    `Don't flaunt it if you're not gonna give it up.`,
    `All aboard the knuckle train to Fist Planet!`,
    `I rode the knuckle train? But I'm in my element!`,
    `Okay, just this once, we'll be vigilantes!`,
    `Nuts, I'm freakin' all about sugar... but I'm even more all about feeding hobos!`,
    `Not to scorn the kicking of people in the crotch?`,
    `Kim, I will destroy you!`,
    `You're the sis, sis.`,
    `Word! Now let's go wreck up that Magic Man!`,
    `Safety! Patrol!`,
    `Shushers, man!`,
    `Slam-bam-in-a-can!`,
    `Have more apple juice. It always makes me feel better when I--Aw! Donny! Quit being a jerk!`,
    `Hands off the housing market!`,
    `Werewolves: much worse than ogres.`,
    `I couldn't let that old man suffer, Jake. My code of honor wouldn't allow it.`,
    `That sounds bombastic, honey!`,
    `She's a radical dame who likes to play games!`,
    `You still up for pixie strangling tomorrow?`,
    `Imagination is for turbo-nerds who can't handle how kick-butt reality is!`,
    `What the hey-hey?`,
    `That riddle sucks.`,
    `I can feel them on my face! Imaginary poison coursing through my veins!`,
    `Makes sense: you do bad stuff, I punish you!`
  ],
  [ // Season 2
    `I'm not evil, Marceline's dad. I'm super good!`,
    `Marceline, release the Finn bomb!`,
    `Well, this ant's about to get in his pants!`,
    `Nobody flicks me in the butt without my consent!`,
    `I'll see you in the Nightosphere, you sick freak!`,
    `I'm also exhausted emotionally, or wait, I mean physically.`,
    `No more pajamas!`,
    `I'm not dead. I'm just all crystal stiff.`,
    `Does it have to be princess hair?`,
    `'Here lies Princess Beautiful. She was so beautiful... but died of baldness?!' Dang it!`,
    `JJ Flip! What the zip?`,
    `He just really likes ice cream.`,
    `Glitter on its own could be evil, but with rainbows... over my dead body!`,
    `Don't just lick stuff!`,
    `That doesn't fair well for their... grade point average.`,
    `It's freaking adorable.`,
    `I'm killing you with ice cream!`,
    `I'm not gonna spank your hams!`,
    `Wands are for wimps!`,
    `Die, you fire!`,
    `The library of the undead!`,
    `I'll just read this book about pigs.`,
    `Jake, we're going to college!`,
    `I can't help it, man! I'm all about stupid!`,
    `Everything small is just a small version of something big! I understand everything!`,
    `I'm better than okay. I know exactly how to impress the princess.`,
    `I'm going to blow your minds.`,
    `A 4-dimensional bubble casts a 3-dimensional shadow! It is beyond comprehension! Beyond space! Beyond time!`,
    `Yes! And their brains are releasing adrenaline, dopamine, even dimethyltryptamine from the pineal gland! This has serious educational value! Thanatophobia and this N.D.E. is giving us euphoric altered awareness! Don't you see, Princess? We were all born to die!`,
    `What? No way. I'm, like, the smartest guy in Ooo thanks to these glasses.`,
    `Huh, knew what? I wrote that list when I was insane with smartness.`,
    `Up, down, left, left, right, right, down, spin, down, up, left, right, left, down, spin, up, down, jump!`,
    `BMO, this game is the worst!`,
    `If I were really in this game, I would crush Sam, breezily, with my mitts!`,
    `Oh, man, BMO, you gotta let us in that game!`,
    `I'm looking at my bits, dude. My leg is math!`,
    `Let's go kick their digital boo-tays!`,
    `Bouncy Bee, Hunny Bunny, they're all hard as butts.`,
    `(to Death) Your brain is stupid!`,
    `You're going down or both of us are going down!`,
    `Marceline, would you do me the honor of getting the plop outta here?`,
    `Marceline... of course! It's been Marceline all along!`,
    `I wish for... the Ancient Psychic Tandem War Elephant!`,
    `No, I'm not! I've got a sweater on!`,
    `Come on, man! That's pervy!`,
    `Thirteen years old? That's how old I am.`,
    `Uh, bleach, lighter fluid, ammonia, gasoline, I dunno. Lady stuff... Plutonium...`,
    `This stink up's mega bamm-bamm to the J-Stop!`
  ],
  [ // Season 3
    `But strength isn't your strength. Adorable cuteness is!`,
    `Hoc habet!`,
    `Eludere!`,
    `I'm a buff baby who can dance like a man!`,
    `Puncha yo buns, puncha yo buns!`,
    `So spice! So spice!`,
    `What the huh?`,
    `That's bunk! Right, Pree-bos?`,
    `Yeah, like pranking him up his face!`,
    `Easy as childbirth.`,
    `I'd rather sanctify PB's lips.`,
    `I'll get your kid back, toy.`,
    `Aw, dude! I broke my stems!`,
    `Yo! Is everyone in church? Worshiping Glob?`,
    `Give it up, Me-Mow! You're only making my face look cooler!`,
    `That idiot's about to walk into the sun.`,
    `One, two, three, four, five, four. Over the mountain, the ominous cloud. Coming to cover the land in a shroud. Hide in a bushel, a basement, a cave. But when cloud comes a hunting, no ones a save, uh, safe. Cloud hunt, gotcha!`,
    `I'll fly the paper, as an airplane, down the bedroom ladder. It'll triple barrel-roll past the kitchen, open the fridge, and cook some eggs; then eat the eggs and unfold itself as it lays on the carpet in front of Marceline's door.`,
    `Disguise yourself, fool! [...] What the-? Dude! You shape-changed to look like me?`,
    `My way!`,
    `Jake! You looted?! That's bad, man! You're supposed to be good cop.`,
    `Gold-darn you, tear ducts! Yah! Yah!`,
    `Dude, I think I have a crush.`
  ],
  [ // Season 4
    `She ain't evil. She's passionate. Help me track her down.`,
    `Oh Jake, Look at her. She’s innocent… like the steam off a puppy’s nose searching for a ham in the snow.`,
    `I'm not trying to. I just like you. I think I... I think I like like you. Listen, when I look at you my brain goes all stupid, and I just want to hug you and sit on the couch and play BMO with you. I can't explain why, but I never felt this way and I think we should be together.`,
    `Why can't I just like a girl?`,
    `No, man. I'll stunt you out!`,
    `Marceline. No one... leaves the Nightosphere!`,
    `We never went steady.`,
    `Hey. What the jug is that?`,
    `I'll hug your mom!`,
    `Oh, whoa so, that means Stormo is like... my son?`,
    `Where did you go, Simon?`,
    `You better get back in the Spirit Hole, dead one.`,
    `Jake! Kerploop!`,
    `LSP... you don't need a mirror to know you look good. (sheathes his sword and grabs Lumpy Space Princess' "dress.") You're beautiful on the inside. Like... your brain and stuff!`,
    `Alvin's hot juice box! Alvin's hot juice box!`,
    `"Uh... Can my Cool Dog and Ancient Scholar defeat your Husker Knights?`,
    `I floop the Pig!`,
    `I activate my Ancient Scholar.... to begin studying and I also move my pig to the Cave of Solitude sooo he can take a nap.`,
    `Well, for one, I think this house is a reflection of your sick brain.`,
    `Bubblegum, I can't do this anymore!`,
    `Now you like me?`,
    `What am I talking about? PB, I was—I was in love with you, okay?! And, you didn't love me back. Now I'm ready to move on, and it's like you're gonna build me up all over again! Well, I'm done! I'm done.`,
    `...Your wavelengths are my weakness. Your emissions are what I've been missing.`,
    `(To weakened Flame Princess) Eh h-hey, what's wrong!? Please say something. Nhgh. Please, I need you... Nhhgh to be okay.`,
    `"Get out of my house, King Worm!"`,
    `Princess, Ricardo's alive, he's in the black ice caves and he's peacocking hardcore!`,
    `Let's crush this mess all accordingly!`,
    `I want bionic legs!`,
    `Naked babies! Naked babies! Naked babies!`,
    `I call fire patrol!`,
    `Shmow-tow, dude! That guy's gonna dingle our bones into tapioca pudding!`,
    `You messed up-ed, Billy!`
  ],
  [ // Season 5
    `I wish...The Lich... never, even ever existed!`,
    `Wait... Wha... Why would The Lich... Jake! Something messed up is happening!`,
    `Oh, what a good boy am I!`,
    `Sometimes a man, just got to retrieve it's own disk...`,
    `I, ate a magic apple by mistake...`,
    `How 'bout BMO and Ice King? (Jake asks) Would they make a good couple?`,
    `(while watching the little people) I did not sleep.`,
    `Hello! Hello, hello, helloo...... ahhhhhHHH (voice scales through several autotuned octaves) (Davey's voice) Hello! I'm Davey!`,
    `Hey Jake, hey Lady.`,
    `Do the splits, thou milk-livered maggot pie!`,
    `Oh crab it to the butternuts, it's locked!`,
    `Man, I don't have patience for this animation junk. Whoever does this must have no life whatsoeve--.`,
    `Escape, Jake, escape!`,
    `(to Ice King) STOP TALKING LIKE A NERD AND GIVE IT TO US STRAIGHT!!!`,
    `Ahem... Hey, Bubs, where's the Ice King? I want to kick his boingloings!`,
    `I guess I'm just thinking about Flame Princess. I told her a joke the other day and she didn't even laugh or anything. Guess it's over between us.`,
    `Oh, well... I... have a girlfriend.`,
    `(as adult Finn) Alphanumeric! Pillow sheep! You have more fluff than sense!`,
    `(as dying Finn) I remember... back... when I was dad.`,
    `I've been going foot nude in the shoe and now I got this turbo huge callous.`,
    `Hey, it's okay BMO, look, Jake and I will make you a funny face.`,
    `We're documenting our creative flow in case we make a break through.`,
    `Yeah, its good, but if we want to be "James Baxter" good, we gotta go deeper.`,
    `We know to figure out how to make our sound force happiness into the listener!`,
    `(written) Bringeth it on, sir!`,
    `Oh, I win! You're so disappointed.`,
    `We were just playing a game, BMO. It all started this morning when Jake made a sign that said-`,
    `Oh cool, that's cool you're dating, that's coool, see ya princess.`,
    `What'ya think of that Braco guy? I mean, he seems kinda weird, and passive and baby lanish, and too unheroic for Peebs. *looks behind him and is shocked* And then I smash that peach!`,
    `That road you're on leads to nowhere.`,
    `You wanna join my primitive noise band?`,
    `(feminine voice) Hello? Oh! Is that the machine part that I ordered?`,
    `(writing) Ac-cep-tance.`,
    `O-ho-ho, was it? Then how do you explain tomorrow's newspaper?`,
    `Jake. A crime has been committed. We must find the criminal.`,
    `Hmm. LSP's injuries were 100 percent emotional. So it has to belong to Pete Sa-something. BMO, take a sample and do a full blood analysis. (in a Jersey accent) The works. (normal accent) Hey, if that guy cut himself during the robbery, he might have gone somewhere to buy a mini adhesive bandage. There's a drugstore across the street!`,
    `What the-?! Jake! What's with all the turning into stuff today?`,
    `Roll the dice, you pay the price.`,
    `Man, we didn't just crack that case, we crunched it! Crumbled it!`,
    `Trespassers get killed mad quick, like zap-zap.`,
    `"Entanglement" is a spell where you get trapped in tree roots, and sometimes they spike out and hook your flesh, and you got to be like, "My body is clay, my spirit feels no pain." Then you chop your way out and kill the wizard!`,
    `Is PB straight-up naked right now?`,
    `I got traumatized by those underpanties.`,
    `Your magicks are powerful, PB.`,
    `Yeah, BMO, show me the stuff, keep it coming!`,
    `C'mon bro, taking pain is easy. You just have to imagine that every bruise is a hickey from the Universe. And everyone wants to get with the Universe.`,
    `Dude, I'm graceful. Mom raised me graceful.`,
    `Dude, what the bjork?`,
    `Jake, it's my special occasion phone! Someone's calling me to tell me about a special occasion.`,
    `Bring it! Yeah, baby, feels good, love it, lovin' that heat on my skull!`,
    `It was weird but I liked it.`,
    `Naw, that's all fine. I just been feeling kind of... gray, is all. Like my inside voice has been kinda quiet lately. Not a lot of instructions forthcoming, y'know?`,
    `I found it in the woods. I named it "Hot Daniel." Anyway, I figured we could do some pretty sick stuff with it.`,
    `Come forth, wizard, and uncurse my mitt! Grassy Mountain Wizard!`,
    `Jeez. Did I just get shown up by Cinnamon Bun?`,
    `Off the dome, here we go. Uh! I'm-a start it now. I'm-a battle now. We gonna make a rhyme, so I can rap this time. I rap for millions... [beat] sesquipedalians.`
  ],
  [ // Season 6
    `Dude, I found out my human dad is still alive.`,
    `Why'd you abandon me in the forest when I was a little baby???`,
    `Thanks a lot, DAD!`
  ]
];
