export default [
  [
    `Actually, I think I'm beating it back with sheer willpower. (grows another lump) Oh, my.`,
    `No! Because no matter how messed up and lumpy I get, this guy never turns his back on me! (turns into Lumpy Jake) Oh yeah. Right behind ya. Just gotta turn my back on this guy.`,
    `Sleds are for suckers! Just ride on my gut!`,
    `Slime Princess, you shouldn't marry Finn. He pees his pants constantly. All the time.`,
    `She got past me, man. I tried to stop her, but she overpowered me.`,
    `Hey! Crack open that book and read something for fun's sake, alright?`,
    `Seriously, Stanley... For a watermelon, you get into trouble way more often than you should.`,
    `(Imitating Princess Bubblegum) Hey, shorty. You should pick your boogers and then fart! (Imitating Ricardio) You look kinda like a big pink baguette!`,
    `I keep finding baby shoes. What the heck, man? And they're all lefties!`,
    `You know what they remind me of? Well-dressed pickles.`,
    `(imitating the Ice King) I'm the Ice King, and I'll never find a bride because I'm such a tool!`,
    `He said "diarrhea."`,
    `Uhh... No. No, she didn't say 'diarrhea who.' She didn't... say it.`,
    `He still cries when he poops. Thanks for being cool, guys.`,
    `This dolphin fell in love with me!`,
    `I wasn't scared! I was singing! I was singing my scream song. Wooaah! Wooaaooh!`,
    `Finn, House-hunting is wiiiild! You've got to try it.`,
    `I'd rather be dancin' with some babes!`,
    `My subconscious must be hungry, huh?`,
    `You guys are so cute, I could just maul you to death.`,
    `Hey, hey. Come on, the ocean is your friend, and you got friends all around you right now. Miles and miles of friends.`,
    `I can't have you messin' up my bread and butter, dude.`,
    `And also swear to only speak in rhymes. Speak in rhymes all the times!`,
    `(deep, Elvis-like voice) Whatever you want, mama.`,
    `Come put her out of her misery, dude.`,
    `Eh. Um. Uh. I choose... sandwich.`,
    `Just hop on my powdered doughnut, boy!`,
    `Nah, we're more like cops. Crooked cops!`,
    `I could probably think of a reason of why that's villainous if you gave me enough time. Maybe...`,
    `I'll kill you and raise your children as my own!`,
    `I'm gonna go rescue all the babies in town. Only the babies.`,
    `Get your hero on, dude!`,
    `Heh heh. I can't take you seriously when you're singing, man.`,
    `Safety! Patrol! Safety patrol! Safety... Oh, were we not wearing the uniforms?`,
    `I have pants! Spun from spider webs... by pixies.`,
    `I wanna help you outta this, man, but she scares the filling outta my doughnut!`,
    `Don't you worry, Finn. I'll get you out of there. I've got a perfect plan! (Marceline sees him & hisses at him, scaring him off) I'm not running away, Finn! This is just part of my plan!`,
    `I saved my bro from a scum-sucking vampire!`,
    `The bazooka goblin has you in its sights!`,
    `Dang girl, if you weren't a figment of my imagination, I'd wanna to have your baby...`,
    `Oh man, I imagined my mom naked! Yuck!`,
    `Dude, be calmed by my saliva.`,
    `Dude, suckin' at something is the first step towards being sorta good at something. You and I are like little baby Billys right now. And we're "sucking" on our first bottle of nonviolent milk.`,
    `I'm not cute, I'll mess you up...`
  ],
  [ // Season 2
    `Hey, get outta here, horse! I wanna go to sleep and you're creeping me the math out!`,
    `Forget it, man. This horse is whack. It's got poobrain.`,
    `Yeah. I know, Finn. I diagnosed this horse with whacked out poobrain 5 minutes ago.`,
    `Dude, let's kill the horse.`,
    `Did you find out that I sleep in the nude? It's none of your business how nude I sleep, Ice King! None of your business!`,
    `You don't just read the poetry to understand it, you got to feel it.`,
    `Then just make it think it's her idea. That's how you make the ladies do what you want.`,
    `Bad computer! No! No! Go sit in the corner, and think about your life.`,
    `Girl, you smell good. Did you take a bath in rainbows and cupcakes?`,
    `Dude, I'm going in.`,
    `Take my sandwich, BMO. I'm gonna go find Fi-- (gasps) A dancing bug!`,
    `Must... find... Finn! Must... must... (voice gets slightly deeper) party foreverrrrrrr!`,
    `If I had a penny for every time someone went crazy, hopped up and magic energy... I'd be Abraham Lincoln.`,
    `Uh-oh. Somebody's gonna do a quest for a frog.`,
    `Gee! Sittin' in this hot sun guarding beans. Boy, it sure beats 26 miles of vanilla ice cream, or caramel ice cream, or peach ice cream.`,
    `This pod makes ice cream outta nothing! It's the goodest thing that's ever happened to me.`,
    `Buddy, just breathe into me.`,
    `Hey, Finn, let's split. This turned out to be boring.`,
    `It's probably a computal gleetch.`,
    `Easy peasy, livin' greasy!`,
    `They're trying to peel me! I'm... not... a... banana!`,
    `We can rule them, like gods...(deep voice) angry gods.`,
    `(Susan Strong falls on the grass) You killed her... Yep. Felled by surface world germs.`,
    `You're sick, Party Pat! I'm gonna go watch T.V.`,
    `Hey man, watch it. I think that's my nerp, but like super stretched out.`,
    `Yeah, I could go for some blood.`,
    `And what if we turn evil? I'll have to start wearing cologne.`
  ],
  [ // Season 3
    `I love you, Everything burrito.`,
    `Wanna just smash 'em all?`,
    `Tastes better than blood! Or does it? Hey Finn, you think blood tastes better than ketchup?`,
    `(mumbling in his sleep) Meat Man. I'm sorry, Meat Man. I didn't mean it, man.`,
    `It's not easy, but you have to be persistent. You might have to defeat a demon lord, or warp through several worlds. But once you do, you walk up the wizard stairs, and produce your magic key you got in the water world and unlock the chamber door. Then, you walk right up to the princess, and give her a smooch. ...Does that make sense?`,
    `Well, I know what's missing. Talent. I'm getting out of here, you hacks. Talentless hacks!`,
    `Oh, I'm coming with you... if only to be disruptive and obnoxious!`,
    `Fish People! I'll be, um... a dolphin!`,
    `Whatever, man. This is a crazy cruise, and Susan is our crazy captain, and I'm a crazy clam shell!`,
    `I'm puttin' an end to all this craziness with my Pick-Axe Hand.`,
    `This ghost ain't home, man.`,
    `Gotta find a honey for my homie! A baby for my buddy! (Deep voice) A lady... for my laddie...`
  ],
  [ // Season 4
    `They're all burned! There's barbequed bods everywhere!`,
    `Love like theirs will always find a way. It will crawl up all over you and drain your body fluids, poisoning you slowly until you pass out. Circle of life, Finn… circle of life.`,
    `Yaaaaaaay! Noooooo!`,
    `Your heart may be small, but it's strong as a bull donk, and I know. You can wait through this line, so we can meet Hunson Abadeer and find out why we're here and why we we're in a pile of bañanles.`,
    `It's not answering questions, man. That thing's gonna bake our beans!`,
    `When you see the wicker devil in the tree afterlife, tell him Jake says, 'Hello.'`,
    `Jakoria will reclaim what we have lost!`,
    `Let me explain some junk about dating. Right now you're at tier one, which is hugging, but pretty soon you'll be at tier two, which is smooching. Then down the road you'll reach tier five, when she'll let you discover all fifteen feet of her long, beautiful stomach. And after a while you'll make it to tier eight where you touch her horn for the very first time. Very special.`,
    `Stay away from that! Do not do tier fifteen!`,
    `Ok, Princess. You need to stop breaking in here!`,
    `Back off Bubblegum, that's his man's biz.`,
    `You heartless monster! Do you have any idea how much he's cried over you? Finn deserves to be happy! Even if his bloopin' face gets burned off. You should be ashamed. You're sick!`,
    `I'm-- puppies?!`,
    `Bad biscuits make the baker broke, bro.`,
    `Your constant harassment of the female gender makes me siiick`,
    `I dreamed I was in kindergarten again, but I had really big feet, and was also the teacher.`
  ],
  [ // Season 5
    `I wish for... a sandwich!`,
    `Oh, what a good boy am I!`,
    `Don't let the dragon drag on.`,
    `Being crazy is hard. You’re getting all hung up, all hung up on imaginary problems. You gotta focus on what’s real, man.`,
    `Hey, a bubble! Pop!`,
    `I look pretty!`,
    `I really like turnin' into cop stuff. I literally can't stop turning into cop stuff.`,
    `Dude, don't make me feel any more awkward than I already do!`,
    `Cram your tram!`
  ]
];
